### ISSUE TITLE
utiLITI still running in processes after closing (utiLITI v0.4.16.1-alpha)

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#249] opened 2019-04-11 12:30 UTC
![closing utiliti](https://user-images.githubusercontent.com/24891656/55957215-0877cf80-5c66-11e9-8923-8871fd4110af.PNG)

I've done several tests to find what triggers it, and it doesn't take much.
To replicate:

- open a .litidata file with creatures in it
- click on a creature and change its appearance
- close utiLITI (no need to save)

The more elements there are on the map, the higher is the effect.

**Comment by TheRamenChef** [comment] 2019-04-13 17:36
I self-assigned this issue because I thought I had a good idea of what was happening. It wasn't what I thought it was, but I did manage to find the root cause: the program is stalling on exit with a "save before quitting" dialogue. This would seem to go against the instruction of the Javadoc for shutdown hooks:

> Shutdown hooks should also finish their work quickly. When a program invokes `exit` the expectation is that the virtual machine will promptly shut down and exit. When the virtual machine is terminated due to user logoff or system shutdown the underlying operating system may only allow a fixed amount of time in which to shut down and exit. It is therefore inadvisable to attempt any user interaction or to perform a long-running computation in a shutdown hook.

I'm assigning someone more familiar with UtiLITI to fix this issue.

**Closed** 2019-04-13 20:33 UTC
Labels: bug
