### ISSUE TITLE
Blank utiLITI window

### ISSUE THREAD

**Issue by PotaytoPrograms** [gurkenlabs/litiengine#347] opened 2020-07-06 08:34 UTC
**Describe the bug**
When utility.jar is opened it just creates a blank window

**To Reproduce**
Simply run the jar

**Expected behavior**
For the utility editor to open

**Your System:**
 - OS:Ubuntu
 - LITIENGINE version:  0.4.20-alpha

**Comment by nightm4re94** [comment] 2020-07-06 22:44
Please provide the Stacktrace generated in the `crash.txt`, as suggested in the bug issue template.

**Comment by PotaytoPrograms** [comment] 2020-07-07 05:48
A crash.txt file was never genrated du to the fact that it did not crash, but instead just shows a blank window

**Comment by nightm4re94** [comment] 2020-07-07 06:32
Okay, maybe the name is misleading. However, the crash.txt is usually generated as soon as any exception comes up, not necessarily crashing the program entirely. It should be located in the same folder as the .jar you are trying to open.
If you open the .jar via console, does it log any errors?

**Comment by PotaytoPrograms** [comment] 2020-07-07 06:52
I have been opening it through terminal since i can;t close it if i open it in any other way and it has never showed any errors.

**Comment by nightm4re94** [comment] 2020-08-17 08:57
Please download the latest release and tell us if the Problem persists. We have tested it on Ubuntu successfully .

**Comment by Gamebuster19901** [comment] 2020-08-19 02:11
Unable to reproduce with:

Ubuntu 18.04.5 LTS
utiLITI v0.5.0-beta

**Comment by nightm4re94** [comment] 2020-08-19 11:39
That's good news! I hope OP will finally be able to use it as well.

**Comment by nightm4re94** [comment] 2020-08-20 06:56
Closing this for now, feel free to reopen if the problem wasn't fixed with the latest release.

**Closed** 2020-08-20 06:56 UTC
Labels: bug
